[project]
name = "llama-stack-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.11.0",
    "fire>=0.7.0",
    "llama-stack-client>=0.2.10",
    "python-dotenv>=1.1.0",
    "requests>=2.32.4",
]
